server:
  port: 8080
  tomcat:
    max-http-form-post-size: 1000MB

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/transaction_test
    username: root
    password: 12345

mybatis:
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true